import type { Metadata } from "next";
import "./globals.css";

import StoreProvider from "@/src/components/StoreProvider/StoreProvider";
import productsService from "@/src/service/ProductService";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const products = await productsService.getProducts();

	return (
		<html lang='en'>
			<body>
				<StoreProvider products={products}>{children}</StoreProvider>
			</body>
		</html>
	);
}
